export const Images = {
  logo: require('./img_logo.png'),
  dark_logo: require('./img_dark_logo.png'),
  logo_fill: require('./img_fill_logo.png'),
  avatar: require('./img_avatar.png'),
  walkthrough01: require('./img_walkthrough_01.png'),
  walkthrough02: require('./img_walkthrough_02.png'),
  walkthrough03: require('./img_walkthrough_03.png'),
  lottie: {
    loading: require('./loading.json'),
    success: require('./success.json'),
    failed: require('./failed.json'),
  },
  doctor_01: require('./img_doctor_01.png'),
  doctor_02: require('./img_doctor_02.png'),
  doctor_03: require('./img_doctor_03.png'),
  doctor_04: require('./img_doctor_04.png'),
  doctor_05: require('./img_doctor_05.png'),
  doctor_06: require('./img_doctor_06.png'),
  doctor_07: require('./img_doctor_07.png'),
  doctor_08: require('./img_doctor_08.png'),
  doctor_09: require('./img_doctor_09.png'),
  doctor_10: require('./img_doctor_10.png'),
  doctor_11: require('./img_doctor_11.png'),
  doctor_12: require('./img_doctor_12.png'),
  doctor_13: require('./img_doctor_13.png'),
  doctor_14: require('./img_doctor_14.png'),
  empty: require('./img_empty.png'),
  video: require('./img_video.png'),
  doctor: require('./img_doctor.png'),
  patient: require('./img_patient.png'),
  google: require('./img_google.png'),
  paypal: require('./img_paypal.png'),
  apple: require('./img_apple.png'),
  mastercard: require('./img_mastercard.png'),
};
